import primitives from "../../primitives";

export const layout = {
  light: {
    "foreground-900": primitives.colors.colors.common.zinc[900],
    "foreground-800": primitives.colors.colors.common.zinc[800],
    "foreground-700": primitives.colors.colors.common.zinc[700],
    "foreground-600": primitives.colors.colors.common.zinc[600],
    "foreground-500": primitives.colors.colors.common.zinc[500],
    "foreground-400": primitives.colors.colors.common.zinc[400],
    "foreground-300": primitives.colors.colors.common.zinc[300],
    "foreground-200": primitives.colors.colors.common.zinc[200],
    "foreground-100": primitives.colors.colors.common.zinc[100],
    "foreground-50": primitives.colors.colors.common.zinc[50],
    overlay: "rgba(0, 0, 0, 0.3)",
    focus: primitives.colors.colors.common.blue[500],
    "focus-op-20": "rgba(0, 111, 238, 0.2)",
    divider: "rgba(17, 17, 17, 0.15)",
    foreground: "#11181C",
    background: primitives.colors.colors.common.white,
  },
  dark: {
    "foreground-900": primitives.colors.colors.common.zinc[50],
    "foreground-800": primitives.colors.colors.common.zinc[100],
    "foreground-700": primitives.colors.colors.common.zinc[200],
    "foreground-600": primitives.colors.colors.common.zinc[300],
    "foreground-500": primitives.colors.colors.common.zinc[400],
    "foreground-400": primitives.colors.colors.common.zinc[500],
    "foreground-300": primitives.colors.colors.common.zinc[600],
    "foreground-200": primitives.colors.colors.common.zinc[700],
    "foreground-100": primitives.colors.colors.common.zinc[800],
    "foreground-50": primitives.colors.colors.common.zinc[900],
    overlay: "rgba(0, 0, 0, 0.3)",
    focus: primitives.colors.colors.common.blue[500],
    "focus-op-20": "rgba(0, 111, 238, 0.2)",
    divider: "rgba(255, 255, 255, 0.15)",
    foreground: "#ECEDEE",
    background: primitives.colors.colors.common.black,
  },
};
